#!/usr/bin/env php
<?php

namespace helvete\Tools;

# Example: ./wage_increase_calc 25000 2018-04 [[[500] 150 1] [DEBUG]]
if (count($argv) < 3) {
    plsHelp($argv[0]);
}
include(__DIR__ . '/Tools/WageCalc.php');
include(__DIR__ . '/Tools/Holidays.php');

$nomiLvl = (int)$argv[1];
$mon = $argv[2];

// static addition to rough wage
define('STADD', isset($argv[3]) ? (double)$argv[3] : 0);
// rate per hour @ vacation
define('VACRATE', isset($argv[4]) ? (double)$argv[4] : 0);
// actual vacation utilization
define('VACUTIL', isset($argv[5]) ? (int)$argv[5] : 0);
// see details of calcualtion
define('DEBUG', isset($argv[6]) && $argv[6] == 'DEBUG');

list($year) = explode('-', $mon);

$hd = new Holidays((int)$year);
$calc = new WageCalc($hd, STADD, VACRATE, VACUTIL, DEBUG);

$actual = $calc->getDiff($nomiLvl, $mon);
if (DEBUG) {
    echo "Pure wage: " . number_format($actual, 2, '.', '');
} else {
    echo $actual;
}
echo PHP_EOL;

function plsHelp($sName) {
    echo <<<HLP
usage: {$sName} wage-amount month [untaxed] [vacation-rate] [vacation-days] [DEBUG]

  wage-amount
    - salary rounded to whole CZK
  month
    - month of calculation, provide in 'YYYY-MM' format
  untaxed
    - amount excluded from tax calculation, various benefits
  vacation-rate
    - hourly reward used to calculate wage for time spent on a vacation
  vacation-days
    - days spent on a vacation within the month being calculated
  DEBUG
    - print calculation details

example: {$sName} 25000 2018-04 500 150 1 DEBUG
HLP;
    echo PHP_EOL;
    exit(2);
}
