#!/usr/bin/env php
<?php
# Example: ./wage_increase_calc 25000 2000 2018-04 [[[500] 150 1] [DEBUG]]
if (count($argv) < 4) {
    plsHelp($argv[0]);
}
include(__DIR__ . '/WageCalc.php');

$nomiLvl = (int)$argv[1];
$rgIncr = (int)$argv[2];
$mon = $argv[3];

// static addition to rough wage
define('STADD', isset($argv[4]) ? (double)$argv[4] : 0);
// rate per hour @ vacation
define('VACRATE', isset($argv[5]) ? (double)$argv[5] : 0);
// actual vacation utilization
define('VACUTIL', isset($argv[6]) ? (int)$argv[6] : 0);
// see details of calcualtion
define('DEBUG', isset($argv[7]) && $argv[7] == 'DEBUG');

$calc = new \helvete\Tools\WageCalc(STADD, VACRATE, VACUTIL, DEBUG);

$actual = $calc->getDiff($nomiLvl, $mon);
$virtual = $calc->getDiff($nomiLvl + $rgIncr, $mon);
if (DEBUG) {
    echo "Pure wage difference: " . number_format($virtual - $actual, 2, '.', '');
} else {
    echo $virtual - $actual;
}
echo PHP_EOL;

function plsHelp($scriptName) {
    echo <<<HLP
usage: {$scriptName} wage-amount increase month [untaxed] [vacation-rate]
    [vacation-days] [DEBUG]

  wage-amount
    - salary rounded to whole CZK
  increase
    - potential salary raise, in whole CZK
  month
    - month of calculation, provide in 'YYYY-MM' format
  untaxed
    - amount excluded from tax calculation, various benefits
  vacation-rate
    - hourly reward used to calculate wage for time spent on a vacation
  vacation-days
    - days spent on a vacation within the month being calculated
  DEBUG
    - print calculation details

example: {$scriptName} 25000 2000 2018-04 500 150 1 DEBUG
HLP;
    echo PHP_EOL;
    exit(2);
}
